grails-app/controllers/org/weceem/user/UserProfileController.groovy
package org.weceem.user

import org.weceem.content.WcmContent
import org.weceem.auth.CMSUser

class UserProfileController {
    static defaultAction = 'edit'
    
    def springSecurityService
    
    def edit = {
        def user = CMSUser.get(springSecurityService.principal.id)
        def recentContent = WcmContent.findAllByCreatedBy(user.username, [max:10, sort:'changedOn', order:'DESC'])
        [CMSUserInstance:user, recentContent: recentContent]
    }
    
    def back = {
        redirect(uri:params.returnURL)
    }
    
    def update = {
        def user = CMSUser.get(springSecurityService.principal.id)

        // @todo Bind only user-editable stuff e.g. password and details, not username or authorities/enabled
        user.properties = params
        user.save(flush:true) // User needs to know if this will fail
        flash.message = 'user.profile.updated'
        redirect(action: edit)
    }
    
    def changePassword = {
    }

    def doChangePassword = { ChangePasswordForm form ->
        if (!form.hasErrors()) {
            assert form.newPass == form.confirmPass // Double double safety check!
            
            def user = CMSUser.get(springSecurityService.principal.id)
            if (springSecurityService.encodePassword(form.current, user.username) == user.passwd) {
                user.pass = form.newPass
                user.save(flush:true) // User needs to know if this will fail
                flash.message = 'user.password.changed'
                redirect(action:'edit')
            } else {
                flash.message = 'user.current.password.incorrect'
                render(view:'changePassword', model:[form:form])
            }
        } else {
            render(view:'changePassword', model:[form:form])
        }
    }
}

grails-app/views/userProfile/_profilefields.gsp
<g:each in="['username', 'firstName', 'lastName', 'email']" var="prop">
    <div class="row">
      <div class="col-md-12 col-xs-12">
        <f:field bean="CMSUserInstance" property="${prop}"/>
      </div>
    </div>
</g:each>

grails-app/views/userProfile/changePassword.gsp
<%@ page import="org.weceem.auth.*" %>

<html>
  <head>
        <meta name="layout" content="weceemadmin"/>
        <link rel="stylesheet" href="${g.resource(dir:'_weceem/css', file:'admin.css').encodeAsHTML()}"/>
        <title><g:message code="user.title.change.password"/></title>
  </head>
  <body>

    <div class="container">
      <div class="row">
        <div class="col-md-12 col-xs-12">
          <!--ui-state-error -->
        </div>
      </div>

      <g:set var="form" value="${new org.weceem.user.ChangePasswordForm()}"/>

      <g:form controller="userProfile" action="doChangePassword" method="POST">
      <input type="hidden" name="id" value="${CMSUserInstance?.id}"/>

      <div class="row">
        <div class="col-md-12 col-xs-12">
          <h1><g:message code="user.title.change.password" encodeAs="HTML"/></h1>
        </div>
      </div>

      <div class="row">
        <div class="col-md-12 col-xs-12">
          <f:field bean="form" property="current">
            <g:passwordField name="current" value="${form.current}"/>
          </f:field>
        </div>
      </div>

      <div class="row">
        <div class="col-md-12 col-xs-12">
          <f:field bean="form" property="newPass">
              <g:passwordField name="current" value="${form.newPass}"/>
          </f:field>
        </div>
      </div>

      <div class="row">
        <div class="col-md-12 col-xs-12">
          <f:field bean="form" property="confirmPass">
             <g:passwordField name="current" value="${form.confirmPass}"/>
          </f:field>
        </div>
      </div>

      <div class="row">
        <div class="col-md-12 col-xs-12">
          <g:actionSubmit class="btn btn-primary" action="doChangePassword"
                            value="${message(code: 'command.save', encodeAs:'HTML')}"/>
          <g:actionSubmit class="btn btn-default" action="edit"
               value="${message(code: 'command.cancel', encodeAs:'HTML')}"/>
        </div>
      </div>
      </g:form>
    </div>
  </body>
</html>

grails-app/views/userProfile/edit.gsp
<%@ page import="org.weceem.auth.*" %>

<html>
    <head>
        <meta name="layout" content="weceemadmin"/>
        <link rel="stylesheet" href="${g.resource(dir:'_weceem/css', file:'admin.css').encodeAsHTML()}"/>
        <title><g:message code="user.title.profile"/></title>
    </head>
    <body>
        <nav:set path="plugin.weceem.weceem_menu/administration" scope="plugin.weceem.weceem_menu"/>
        <div class="container">
          <div class="row">
            <div class="col-md-12 col-xs-12">
                <!--ui-state-error -->
            </div>
          </div>

          <g:form controller="userProfile" action="update" method="POST">
            <input type="hidden" name="id" value="${CMSUserInstance?.id}"/>
            <input type="hidden" name="returnURL" value="${returnURL}"/>

            <div class="row">
              <div class="col-md-12 col-xs-12">
                <h1><g:message code="user.title.profile" encodeAs="HTML"/></h1>
              </div>
            </div>

            <div class="row">
              <div class="col-md-12 col-xs-12">
                <g:render template="profilefields"/>
              </div>
            </div>

            <div class="row">
              <div class="col-md-12 col-xs-12">
                <g:actionSubmit class="btn btn-primary" action="update"
                            value="${message(code: 'command.save', encodeAs:'HTML')}"/>
                <g:actionSubmit class="btn btn-default" action="back"
                            value="${message(code: 'command.back', encodeAs:'HTML')}"/>
              </div>
            </div>

          </g:form>

          <div class="row">
            <div class="col-md-12 col-xs-12">
              <h2>Your content</h2>
              <ul>
                <g:each in="${recentContent}" var="c">
                    <li><g:link controller="wcmEditor" action="edit" id="${c.id}">${c.title.encodeAsHTML()}</g:link>
                </g:each>
              </ul>

              <g:link action="changePassword">Change your password</g:link>
            </div>
          </div>
        </div>
    </body>
</html>